version: "3.9"

services:

  api-service:
    build: ./api-service
    container_name: image-api-container

    ports:
      - "5000:5000"

    restart: always

  worker-service:
    build: ./worker-service
    container_name: image-worker-container

    restart: always